### PR TITLE
fix: simplify survey form

### PR DESCRIPTION
**Pull request by obdulia-losantos**
First part of: https://jira.ehealthafrica.org/browse/GTH-195

### CODE REVIEW

**Comment by obdulia-losantos** [comment]
Is this what you want @sabeen ?

### Initial
image

### Uploaded new file and media files
image

For me is not so much clear that I have uploaded a new xform version :thinking:

**Comment by shawnsarwar** [comment]
@obdulia-losantos Is the question to @sabeen resolved? Anything outstanding on this before it's reviewed?

**Comment by obdulia-losantos** [comment]
1. Not yet
2. Nothing else pending

**Comment by sabeen** [comment]
sorry, haven't seen the comment. Yes, this is what I wanted. It was strange to have the delete icon of the new form next to the delete icon of the whole form. So I've put it to the left hand side, where all the other information is.

**Review by shawnsarwar — APPROVED** [review]

**Comment by shawnsarwar** [comment]
:tada:

**Comment by obdulia-losantos** [comment]
@lordmallam do you want to review it?

**Pull request merged**
