### PR TITLE
chore: implement auto release

### PR DESCRIPTION
**Pull request by obdulia-losantos**
Before merging this PR the Travis credentials must be updated, the current ones correspond to the read only user. We can always merge it but the travis deploy job will fail till we fix the settings.

- `DOCKER_HUB_USER`
- `DOCKER_HUB_PASSWORD`

### CODE REVIEW

**Review by admbtlr — DISMISSED** [review]
looks good!

**Comment by obdulia-losantos** [comment]
@MrPink did you have time to change Travis settings? :grimacing:

**Comment by obdulia-losantos** [comment]
@adamvert @tremolo ready? :see_no_evil:

**Comment by admbtlr** [comment]
Yep!

**Comment by obdulia-losantos** [comment]
I need at least one approval :stuck_out_tongue:

**Review by admbtlr — APPROVED** [review]

**Pull request merged**
