### PR TITLE
feat: add keyboard shortcut to modals

### PR DESCRIPTION
**Pull request by obdulia-losantos**
Closes: https://jira.ehealthafrica.org/browse/GTH-118

Warning:
https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event

### CODE REVIEW

**Comment by admbtlr** [comment]
This isn't totally working for me - for example, if I try to delete a surveyor, I get a _Are you sure you want to delete the surveyor?_ modal. I can press _escape_ to cancel it, but pressing _enter_ doesn't do anything.

**Comment by obdulia-losantos** [comment]
I'll take a look :sob:

**Comment by obdulia-losantos** [comment]
I was using `charCode` that it's also deprecated. It was working when I tested it locally but now with the last browser release it was removed :anguished: 

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode

**Review by admbtlr — COMMENTED** [review]
Yay! Now can we have this in Aya too? 😅

**Review by admbtlr — APPROVED** [review]

**Pull request merged**
